= EniBook : éléments HTML
:docinfo:
:example-caption: Exemple
:icons: font
:nofooter:
:sectnums:
:source-highlighter: highlightjs-ext
:stem: latexmath
:stylesdir: styles/
:stylesheet: asciidoctor.css
:toc: left
:toc-title!: 
:toclevels: 2
:xrefstyle: full

Les composants EniBook sont des link:https://developer.mozilla.org/fr/docs/Web/Web_Components/Using_custom_elements[éléments HTML personnalisés] (_custom element_) représentés par des balises du type `_<element-name-it></element-name-it>_` dont le nom se termine toujours par le suffixe `-it`.

Les développements sont réalisés en
link:https://www.typescriptlang.org[`typescript`] et sont accessibles depuis l'link:http://127.0.0.1:5500/packages/docs/api/index.html[API] (_Application Programming Interface_).



stem:[\displaystyle\cos(\frac{1}{1+x^2}\times \frac{1}{x^3})]

////
++++
<typescript-it>
  <script type="enibook/src">
    const l: number = 3
    l
  </script>
</typescript-it>
++++
////

++++
<javascript-it>
  <script type="enibook/src">
    console.info('information')
    console.warn('avertissement')
    console.assert('assertion', 1+1 === 3)
    console.debug('debug')
    function f(x) { return 2*x + 5 }
    console.log("f(3)",f(3))
    f(3)
  </script>
</javascript-it>
++++


////
++++
<python-it>
  <script type="enibook/header">
    <p>
      Your name is : <input id="zone" autocomplete="off">
      <button id="test">click !</button>
    </p>
  </script>

  <script type="enibook/src">
    from browser import document, alert
    from browser.widgets.dialog import InfoDialog

    def echo(ev):
      InfoDialog("Hello", f"Hello {document['zone'].value} !")

    document["test"].bind("click", echo)
  </script>
</python-it>
++++
////

////
++++
<playground-it language="html" head-filename="templates/frame-head.html">
  <script type="enibook/src">
  <h1>Titre</h1>
  <h2>Section</h2>
  <p>Un petit paragraphe.</p>

  <ol>
    <li>un item</li>
    <li>deux</li>
  </ol>
  </script>
</playground-it>
++++



++++
<frame-it url="https://enibook.org" head-filename="templates/frame-head.html" border>
  <script type="frame-it/main">
    <p>Hello, world !</p>
  </script>
  <script type="frame-it/footer">
    <code-it language="python" read-only theme="light">
      <script type="code-it/src">
        def f(x):
          return 3*x
      &lt;/script&gt;
    </code-it>
    <lorem-ipsum-it count=3></lorem-ipsum-it>
  </script>
</frame-it>
++++

++++
<code-it fieldset language="html">
  <script type="code-it/src">
  <h1>Titre</h1>
  <h2>Section</h2>
  <p>Un petit paragraphe.</p>

  <ol>
    <li>un item</li>
    <li>deux</li>
  </ol>
  </script>
</code-it>
++++

++++
<code-it language="python" read-only theme="light">
  <script type="code-it/src">
    def f(x):
      return 3*x
  </script>
</code-it>
++++
////

include::./toggle/toggle.adoc[]
// include::./code/code.adoc[]
include::./clock/clock.adoc[]
include::./lorem-ipsum/lorem-ipsum.adoc[]
include::./toolbar/toolbar.adoc[]
