:fn-sens-de-lecture: pass:c,q[footnote:[Selon le sens de lecture -- de gauche à droite (``ltr`` : _left to right_) ou de droite à gauche (``rtl`` : _right to left_) -- le code source sera à gauche pour une lecture de gauche à droite, à droite pour une lecture de droite à gauche. Le sens de lecture -- de gauche à droite (``ltr`` : _left to right_) ou de droite à gauche (``rtl`` : _right to left_) -- dépend de la langue retenue pour les éléments. Par exemple, le français, l'anglais ou l'espagnol se lisent de gauche à droite tandis que l’arabe, le farsi, l’ourdou ou l’hébreu se lisent de droite à gauche.]]
:fn-clic-souris: pass:c,q[footnote:[Le clic se fait à l'aide du bouton principal de la souris : le gauche en mode droitier, le droit en mode gaucher, ou le bouton unique.]]

== Aperçu asciidoc

[%header,cols="2a,1a,1a"]
|===
| Fonction
| Elément ``html``
| Classe ``typescript``

| Cet élément présente côte à côte un code source `asciidoc` à interpréter et le rendu de son interprétation en `html`.

++++
<adoc-preview-it>
  <script type="enibook">
    du code *_asciidoc_*
  </script>
</adoc-preview-it>
++++

Le transcodage `asciidoc` -> `html` est réalisé par le processeur https://docs.asciidoctor.org/asciidoctor.js/latest/[asciidoctor].
| ``<adoc-preview-it>``

type : « link:https://developer.mozilla.org/fr/docs/Glossary/Block-level_content[bloc] » (_block-level element_)
| link:api/classes/AdocPreviewIt.html[``AdocPreviewIt``]
|===


[%collapsible]
.Structure
====
L'élément est structuré en deux parties :

- à gauche{fn-sens-de-lecture}, le code source à interpréter;
- à droite, l'aperçu de l'interprétation du code source.

Les deux parties sont séparées par une barre verticale munie d'un grip +++<it-mdi-drag-vertical style="width:24px" title="grip vertical"></it-mdi-drag-vertical>+++.

++++
<adoc-preview-it>
  <script type="enibook">
    // code asciidoc
    = Asciidoc

    == Titre de section
    .Liste _asciidoc_
    * item de liste
    * autre item
    * lien https://docs.asciidoctor.org/asciidoc/latest/[pour en savoir plus...]
  </script>
</adoc-preview-it>
++++
====

[%collapsible]
.Interactivité
====
Cet élément est interactif : il est cliquable 
+++<it-mdi-mouse style="width:24px" title="non cliquable"></it-mdi-mouse>+++ 
mais non éditable 
+++<it-mdi-keyboard-off-outline style="width:24px" title="non éditable"></it-mdi-keyboard-off-outline>+++.

L'interaction consiste à adapter les largeurs respectives des parties gauche et droite.

- Quand on passe la souris sur l'élément, ses bords ainsi que la barre verticale qui sépare les deux parties, sont mis en évidence par une coloration différente.
- La barre verticale est déplaçable horizontalement. Quand on passe la souris sur la barre (y compris sur son grip central), le curseur de la souris change de forme pour signifier un déplacement horizontal possible : +++<it-mdi-resize-horizontal></it-mdi-resize-horizontal>+++.
+
Pour déplacer la barre séparatrice, on opère par glissement de la souris : il suffit de cliquer{fn-clic-souris} sur cette barre footnote:[Le grip vertical +++<it-mdi-drag-vertical></it-mdi-drag-vertical>+++ est présent pour faciliter le déplacement de la barre verticale séparatrice.], maintenir le bouton de la souris enfoncé et ne le relâcher que lorsque le pointeur a atteint la position désirée pour la barre verticale.
+
Le déplacement est limité pour laisser au moins un quart de la largeur totale à la partie la moins large.
====

=== Script ``enibook``
Le code source à visualiser peut être défini dans le contenu de la balise ``adoc-preview-it`` à l'aide d'un script de type ``enibook``.

[source,html]
----
<adoc-preview-it>
  <script type="enibook">
    // le code asciidoc à interpréter et à visualiser
  </script>
</adoc-preview-it>
----

[#ex-adoc1%collapsible]
.Exemple de code défini par un script ``enibook``
====
++++
<html-preview-it>
  <script type="enibook">
    <adoc-preview-it>
      <script type="enibook">
        Du code *_asciidoc_*
      &lt;/script&gt;
    </adoc-preview-it>
  </script>
</html-preview-it>
++++
====


=== Attributs et propriétés
Cette balise possède 3 attributs spécifiques optionnels : ``position``, ``src`` et ``theme``.

==== Code source
L'attribut ``src`` permet de définir le code source à visualiser à partir d'un fichier extérieur.

[%collapsible]
.Exemple de code issu d'un fichier
====
.Fichier ``adoc-preview-file.txt``
[source,html]
----
include::adoc-preview-file.txt[]
----

++++
<html-preview-it>
  <script type="enibook">
    <adoc-preview-it src="adoc-preview/adoc-preview-file.txt">
    </adoc-preview-it>
  </script>
</html-preview-it>
++++
====

Il est possible de combiner l'utilisation d'un script ``enibook`` et l'attribut ``src``. Dans ce cas, le contenu du fichier est inséré avant le contenu du script comme dans l'exemple ci-dessous.

[%collapsible]
.Exemple de codes issus d'un script et d'un fichier
====
++++
<html-preview-it>
  <script type="enibook">
    <adoc-preview-it src="adoc-preview/adoc-preview-file.txt">
      <script type="enibook">
        Paragraphe ajouté par le script `enibook`
      &lt;/script&gt;
    </adoc-preview-it>
  </script>
</html-preview-it>
++++
====

En dernier ressort, le code source à visualiser peut être défini par un script ``javascript`` à l'aide de la propriété ``code`` de la classe ``AdocPreviewIt``.

[%collapsible]
.Exemple de code défini par programme
====
++++
<html-preview-it id="demo-prop">
  <script type="enibook">
    <!-- visualisateur sans code -->
    <adoc-preview-it class="demo"></adoc-preview-it>
    <!-- ajout du code par script javascript -->
    <script type="text/javascript">
      const demo = document.body.querySelector("#demo-prop")
      const preview = demo.shadowRoot.querySelector("adoc-preview-it")
      preview.code = `
Code source ajouté par la propriété \`code\` : 

du code *_asciidoc_*.
`
    &lt;/script&gt;
    <!-- ajout d'un style -->
    <style>
      .demo { padding: 0.5em; background-color: lightcyan; }
    </style>
  </script>
</html-review-it>
++++
====

==== Position du séparateur vertical
La position initiale du séparateur entre le code source et son aperçu est définie par l'attribut ``position``, exprimé en % de la largeur de l'élément (comprise entre 25 et 75, 50 par défaut).

[%collapsible]
.Exemple d'utilisation de l'attribut `position`
====
++++
<html-preview-it>
  <script type="enibook">
    <adoc-preview-it position=75>
      <script type="enibook">
        du code *_asciidoc_*
      &lt;/script&gt;
    </adoc-preview-it>
  </script>
</html-preview-it>
++++
====

==== Thème du code source
Le thème de colorisation du code source (clair : `light` ou sombre : `dark`) est précisé par l'attribut `theme` (`dark` par défaut).

[%collapsible]
.Exemple d'utilisation de l'attribut `theme`
====
Mode clair:: {empty}
+
++++
<html-preview-it>
  <script type="enibook">
    <adoc-preview-it theme="light">
      <script type="enibook">
        du code *_asciidoc_* en mode clair
      &lt;/script&gt;
    </adoc-preview-it>
  </script>
</html-preview-it>
++++

Mode sombre:: {empty}
+
++++
<html-preview-it>
  <script type="enibook">
    <adoc-preview-it theme="dark">
      <script type="enibook">
        du code *_asciidoc_* en mode sombre
      &lt;/script&gt;
    </adoc-preview-it>
  </script>
</html-preview-it>
++++
====

=== API
L'link:https://developer.mozilla.org/fr/docs/Glossary/API[API] (_Application Programming Interface_) de l'élément ``<adoc-preview-it>`` est
consultable link:../api/classes/AdocPreviewIt.html[ici].

.L'API en bref
[%collapsible]
====
++++
<api-viewer
src="_dist/custom-elements.json"
only="adoc-preview-it"
exclude-knobs="src"
>
  <template data-element="adoc-preview-it" data-target="host">
    <adoc-preview-it>
      <script type="enibook">
        Du code *_asciidoc_*
      </script>
    </adoc-preview-it>
  </template>
</api-viewer>
++++
====

.Usage en ``typescript``
[%collapsible]
====
[source,typescript]
----
import { AdocPreviewIt } from '@enibook/elements/dist/elements/adoc-preview/adoc-preview' // <1>
const adocPreview = new AdocPreviewIt() // <2>
adocPreview.code = `
Le code \`asciidoc\` à visualiser
`                                       // <3>
document.body.appendChild(adocPreview)  // <4>
/*
<body>
...
<adoc-preview-it>
  <script type="enibook">
    Le code `asciidoc` à visualiser
  </script>
</adoc-preview-it>
</body>
*/
----
<1> importer la classe link:../api/classes/AdocPreviewIt.html[``AdocPreviewIt``];
<2> créer une instance de cette classe;
<3> définir le code à visualiser;
<4> ajouter l'instance dans le link:https://developer.mozilla.org/fr/docs/Web/API/Document_Object_Model[DOM].
====


