// clock-it
:fn-affichage-date: pass:c,q[footnote:[La manière d'afficher ces 4 informations dépend de la langue considérée. Par exemple, le ``dimanche 20 décembre 2020`` en français s'écrira ``Sunday, 20 December 2020`` en anglais, ``Sonntag, 20. Dezember 2020`` en allemand, ``domingo, 20 de diciembre de 2020`` en espagnol ou encore ``2020年12月20日 日曜日`` en japonais.]]
:fn-sens-de-lecture: pass:c,q[footnote:[Le sens de lecture -- de gauche à droite (``ltr`` : _left to right_) ou de droite à gauche (``rtl`` : _right to left_) -- dépend de la langue retenue pour les éléments. Par exemple, le français, l'anglais ou l'espagnol se lisent de gauche à droite tandis que l’arabe, le farsi, l’ourdou ou l’hébreu se lisent de droite à gauche.]]
:fn-sens-de-lecture-chevron: pass:c,q[footnote:[Selon le sens de lecture -- de gauche à droite (``ltr`` : _left to right_) ou de droite à gauche (``rtl`` : _right to left_) -- le chevron est situé à l'extrémité droite pour une lecture de gauche à droite, à l'extrémité gauche pour une lecture de droite à gauche.]]
:fn-sens-de-lecture-coche: pass:c,q[footnote:[Selon le sens de lecture -- de gauche à droite (``ltr`` : _left to right_) ou de droite à gauche (``rtl`` : _right to left_) -- la coche est situé à gauche de l'item pour une lecture de gauche à droite, à droite de l'item pour une lecture de droite à gauche.]]

== Horloge

[%header,cols="2a,1a,1a"]
|===
| Fonction
| Elément ``html``
| Classe ``typescript``

| Cet élément affiche une horloge numérique indiquant l'heure et la date courantes.

+++<clock-it time date></clock-it>+++
| ``<clock-it>``

type : « link:https://developer.mozilla.org/fr/docs/Glossary/Inline-level_content[en ligne] » (_inline-level element_)
| link:../api/classes/ClockIt.html[``ClockIt``]
|===

[%collapsible]
.Structure
====
- A gauche de l'icône +++<it-mdi-calendar-clock-outline></it-mdi-calendar-clock-outline>+++, la date est affichée sous la forme ``jour quantième mois année``{fn-affichage-date} où ``jour`` est le nom du jour (lundi, mardi...), ``quantième`` le numéro du jour dans le mois (1, 2...), ``mois`` le mois  en toutes lettres (janvier, février...) et ``année`` l'année en chiffres
(exemples: ``jeudi 8 juin 2023``, ``mercredi 5 avril 2034``).

- A droite de l'icône +++<it-mdi-calendar-clock-outline></it-mdi-calendar-clock-outline>+++, l'heure est présentée sous la forme ``hh:mm:ss`` où ``hh`` représente l'heure avec deux chiffres, ``mm`` les minutes avec deux chiffres et ``ss`` les secondes également avec deux chiffres (exemples: ``08:12:54``, ``13:02:05``).
====

[%collapsible]
.Interactivité
====
Cet élément est cliquable +++<it-mdi-mouse title="cliquable"></it-mdi-mouse>+++ mais non éditable  +++<it-mdi-keyboard-off-outline title="non éditable"></it-mdi-keyboard-off-outline>+++.
L'interaction consiste à adapter l'affichage de l'horloge aux besoins de l'utilisateur.

L'horloge est un bouton cliquable à 4 états. 
En cliquant sur l'horloge, on passe successivement dans les états suivants :

. affichage de l'heure uniquement : +++<clock-it time></clock-it>+++
. affichage de la date et de l'heure : +++<clock-it time date></clock-it>+++ 
. affichage de la date uniquement : +++<clock-it date></clock-it>+++
. affichage de l'icône uniquement :  +++<clock-it></clock-it>+++

====

=== Attributs et propriétés
Cette balise possède 3 attributs spécifiques optionnels : ``date``, ``size`` et ``time``.

==== Taille de l'horloge
L'attribut `size` (`small` par défaut, `medium` ou `large`) précise la taille de l'horloge.

++++
<html-preview-it position="60">
  <script type="enibook">
    <p><clock-it size="small"></clock-it></p>

    <p><clock-it size="medium"></clock-it></p>

    <p><clock-it size="large"></clock-it></p>
  </script>
</html-preview-it>
++++

==== Réglage de l'affichage
* L'attribut `date` permet d'afficher la date.
* L'attribut `time` permet d'afficher l'heure.

++++
<html-preview-it position="60">
  <script type="enibook">
    <p><clock-it date></clock-it></p>

    <p><clock-it time></clock-it></p>

    <p><clock-it date time></clock-it></p>
  </script>
</html-preview-it>
++++


=== API
L'link:https://developer.mozilla.org/fr/docs/Glossary/API[API] (_Application Programming Interface_) de l'élément ``<clock-it>`` est
consultable link:../api/classes/ClockIt.html[ici].

.L'API en bref
[%collapsible]
====
[cols="1a"]
|===
|
++++
<api-viewer
src="dist/custom-elements.json"
only="clock-it"
>
</api-viewer>
++++
|===
====

.Usage en ``typescript``
[%collapsible]
====
[cols="100a"]
|===
|
[source,typescript]
----
import { ClockIt } from '@enibook/elements/dist/elements/clock/clock' // <1>
const clock = new ClockIt()                                           // <2>
clock.size = 'large'                                                  // <3>
clock.date = true                                                     // <4>
document.body.appendChild(clock)                                      // <5>
/*
<body>
...
<clock-it size="large" date></clock-it>
</body>
*/
----
<1> importer la classe link:../api/classes/ClockIt.html[``ClockIt``];
<2> créer une instance de cette classe;
<3> préciser la taille de l'instance;
<4> préciser le type affichage désiré;
<5> ajouter l'instance dans le link:https://developer.mozilla.org/fr/docs/Web/API/Document_Object_Model[DOM].
|===
====
